proxmox_api_host: "10.19.59.200"
proxmox_api_user: "{{ vault_proxmox_api_user | default('ansible@pve') }}"
proxmox_validate_certs: false

proxmox_default_node: "proxmox"
proxmox_storage: "vm-storage"
proxmox_bridge: "vmbr0"