# -------------------------------------------------------------------
#
# Autrice     : Lucielle Anya Alita Ahsoka Voeffray
# Date        : 19.05.2026
# Version     : 0.3.6
# Description : Fichier de config des enseignants
#
# -------------------------------------------------------------------

# NomPrénom, afin d'attribuer les VMs aux enseignants
vmconf_teacher_username: "VoeffrayLucielle"

# Classe à laquelle les VM sont dédiées
vmconf_class: "INFO-BI32"

# Module enseigné
vmconf_module: "R01d"

# Nombre de VM à créer
vmconf_nbr_vm: 25
vmconf_first_vmid: 5000

# Utilisateur Administrateur des VMs et son mot de passe
vmconf_user: "Administrator"
vmconf_password: "Emf12345"

# Enlever le # si vous voulez utiliser le VMNet1
vmconf_vmnet: "VMNet1"
vmconf_subnet: "10.19.56" # Le subnet ne doit pas avoir le .0/24 final
vmconf_gateway: "10.19.56.1"

# Enlever le # si vous voulez utiliser le VMNet2
#vmconf_vmnet: "VMNet2"
#vmconf_subnet: "10.19.57" # Le subnet ne doit pas avoir le .0/24 final
#vmconf_gateway: "10.19.57.1"
