# -----------------------------------------------------------------
#
# Autrice     : Lucielle Anya Alita Ahsoka Voeffray
# Date        : 18.05.2026
# Version     : 0.3.5
# Description : Variables à utiliser dans les playbooks
#
# -----------------------------------------------------------------

---
proxmox_api_hosts:
  - 10.19.59.240
  - 10.19.59.241
  - 10.19.59.242

proxmox_nodes:
  - "a41-srv-01"
  - "a41-srv-02"
  - "a41-srv-03"

proxmox_api_host: 10.19.59.240
proxmox_api_port: 8006
proxmox_validate_certs: false

proxmox_api_user: "{{ vault_proxmox_api_user }}"
proxmox_api_token_secret: "{{ vault_proxmox_api_token_secret }}"
proxmox_api_token_id: "{{ vault_proxmox_api_token_id }}"

proxmox_template_node: "a41-srv-01"
proxmox_storage: "vm_storage"
proxmox_default_bridge: "vmnet1"
proxmox_pool: "ansible-vms"
proxmox_state: started

proxmox_template_2k25: 102

proxmox_vm_name_separator: "-"
