---
- name: Cloner la VM
      community.proxmox.proxmox_kvm:
        # Informations de connexion à proxmox
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        validate_certs: "{{ proxmox_validate_certs }}"

        # Annonce quant à la node à utiliser
        node: "{{ proxmox_default_node }}"
        
        # ID du template à cloner
        clone: true
        vmid: "{{ proxmox_template_2k25 | int }}"
        full: true
        
        # Nom de la VM, n'est pas unique, il sert à retrouver les VM à détruire
        name: "{{ (vmname_parts + ['%02d' | format(item)]) | join(vmname_separator) }}"

        # Définir le network à utiliser
        net:
          net0: "virtio,bridge={{ vmconf_vmnet }}"

        # Ajouter le disque cloudinit
        ide:
          ide2: "{{ proxmox_storage }}:cloudinit"

        # Informations pour Cloudbase-init
        ciuser: "{{ vmconf_user }}"
        cipassword: "{{ vmconf_password }}"
        ipconfig:
          ipconfig0: "ip={{vmconf_subnet}}.{{item + 10}}/24,gw={{ vmconf_gateway }}"

        # Utiliser le stockage prévu pour les VMs
        storage: "{{ proxmox_storage }}"
        pool: "{{ proxmox_pool }}"

        # tags pour retrouver les VMs plus facilement
        tags:
          - "{{ vmconf_module | lower }}"
          - "{{ vmconf_class | lower }}"
          - "{{ vmconf_teacher_username | lower }}"
        
        # Demander à ce que la VM soit existente avant de passer à la prochaine
        # VM
        state: present

        timeout: 900