
#-------------------------------------------------------------------------------------
#
# Autrice     : Lucielle Anya Alita Ahsoka Voeffray
# Date        : 18.05.2026
# Version     : 0.1.0
# Description : Liste des collections Ansibles requises pour tourner ces playbooks
#
#-------------------------------------------------------------------------------------

---
collections:
  - name: community.proxmox
