---

- name: Cloner la VM
  community.proxmox.proxmox_kvm:
    # Informations de connexion à proxmox
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs }}"

    # Annonce quant à la node à utiliser
    node: "{{ proxmox_template_node }}"

    # La nouvelle VM doit être créée sur ce nœud
    target: "{{ current_vm_node }}"

    # ID du template à cloner
    clone: true
    vmid: "{{ proxmox_template_2k25 | int }}"
    full: false

    # Nom de la VM, est unique, il sert à retrouver les VM à détruire
    name: "{{ (vmname_parts + ['%02d' | format(vm_number)]) | join(vmname_separator) }}"
    newid: "{{ vmconf_first_vmid | int + vm_number | int }}"

    # Définir le network à utiliser
    net:
      net0: "virtio,bridge={{ vmconf_vmnet }}"

    # Utiliser le stockage prévu pour les VMs
    # storage: "{{ proxmox_storage }}"
    pool: "{{ proxmox_pool }}"

    # Demander à ce que la VM soit existente avant de passer à la prochaine
    # VM
    state: present

    # Augmenter la timeout car copier 60Go de données prend + de 30 secondes
    timeout: 900

- name: Ajouter le disque Cloud-Init
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs }}"

    node: "{{ current_vm_node }}"
    vmid: "{{ vmconf_first_vmid | int + vm_number | int }}"

    ide:
      ide2: "{{ proxmox_storage }}:cloudinit"

    update_unsafe: true
    update: true
    state: present
    api_timeout: 60

- name: Configurer Cloud-Init
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs }}"
    node: "{{ current_vm_node }}"
    vmid: "{{ vmconf_first_vmid | int + vm_number | int }}"
    ciuser: "{{ vmconf_user }}"
    cipassword: "{{ vmconf_password }}"
    ipconfig:
      ipconfig0: "ip={{ vmconf_subnet }}.{{ vm_number + 10 }}/24,gw={{ vmconf_gateway }}"
    update: true

- name: Appliquer les tags à la VM
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs }}"

    node: "{{ current_vm_node }}"
    vmid: "{{ (vmconf_first_vmid | int) + (vm_number | int) }}"

    tags:
      - "{{ vmconf_module | lower }}"
      - "{{ vmconf_class | lower }}"
      - "{{ vmconf_teacher_username | lower }}"

    update: true
    state: present

- name: Ajouter la VM à la haute disponibilité
  community.proxmox.proxmox_cluster_ha_resources:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs }}"

    name: "{{ vmconf_first_vmid | int + vm_number | int }}"
    state: present
    hastate: started

    max_restart: 1
    max_relocate: 1
